# Generated by Django 5.2 on 2025-04-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('revenue_target', models.FloatField()),
                ('revenue_sales', models.FloatField()),
                ('revenue_ratio', models.FloatField()),
                ('cost_cost', models.FloatField()),
                ('cost_goods', models.FloatField()),
                ('cost_outsourcing', models.FloatField()),
                ('sgna', models.FloatField()),
                ('op_target', models.FloatField()),
                ('op_operating_profit', models.FloatField()),
                ('op_ratio', models.FloatField()),
                ('op_margin', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
